# Generated by Django 2.1.5 on 2019-11-26 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
