# Generated by Django 2.1.5 on 2019-11-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_favourites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
