# Generated by Django 2.2.7 on 2019-12-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('product_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'favourite',
                'db_table': 'favourites',
                'managed': True,
            },
        ),
    ]
