# Generated by Django 2.2.7 on 2019-12-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='image1',
            field=models.FileField(blank=True, help_text='Upload only .png, .jpg & .jpeg image extension.', null=True, upload_to='image/ad_image'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='image2',
            field=models.FileField(blank=True, help_text='Upload only .png, .jpg & .jpeg image extension.', null=True, upload_to='image/ad_image'),
        ),
    ]
