# Generated by Django 2.1.5 on 2019-12-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191205_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
