# Generated by Django 2.1.5 on 2019-12-06 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191206_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='date_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
