# Generated by Django 2.1.5 on 2019-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191206_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
