# Generated by Django 2.1.5 on 2019-12-06 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20191206_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
